/* Generated by Cython 0.24.1 */

#ifndef __PYX_HAVE__chainer_tagger
#define __PYX_HAVE__chainer_tagger


#ifndef __PYX_HAVE_API__chainer_tagger

#ifndef __PYX_EXTERN_C
  #ifdef __cplusplus
    #define __PYX_EXTERN_C extern "C"
  #else
    #define __PYX_EXTERN_C extern
  #endif
#endif

#ifndef DL_IMPORT
  #define DL_IMPORT(_T) _T
#endif

__PYX_EXTERN_C DL_IMPORT(void) tag(char const *, char const *, int, float *);
__PYX_EXTERN_C DL_IMPORT(void) tag_doc(char const *, char const **, int *, int, float **);
__PYX_EXTERN_C DL_IMPORT(void) tag_and_parse_doc(char const *, char const **, int *, int, float **, float **);

#endif /* !__PYX_HAVE_API__chainer_tagger */

#if PY_MAJOR_VERSION < 3
PyMODINIT_FUNC initchainer_tagger(void);
#else
PyMODINIT_FUNC PyInit_chainer_tagger(void);
#endif

#endif /* !__PYX_HAVE__chainer_tagger */
